[package]
name = "recognising_sounds"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
ndarray = "0.16.1"
palette = "0.7.6"
plotters = "0.3.7"
rand = "0.8.5"
rustfft = "6.2.0"
smartcore = "0.4.0"
statrs = "0.18.0"
